name: PR Check
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-check:
    runs-on: ubuntu-24.04
    name: Test and Check
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build Package
        run: pnpm build

      - name: Type Check
        run: pnpm tsc --noEmit

      - name: Run Tests
        run: pnpm test
        
      - name: Verify Package Signature
        run: pnpm audit signature -P